kitchen_app/urls.py
from django.urls import path, include

from kitchen_app.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeDeleteView,
    DishTypeCreateView,
    CooksListView,
    CooksDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    IngredientsListView,
    IngredientsCreateView,
    IngredientsDeleteView,
    toggle_assign_to_dish
)

urlpatterns = [
    path("", index, name="home_page"),
    path("menu/", DishListView.as_view(), name="dish_list"),
    path("menu/<int:pk>/", DishDetailView.as_view(), name="dish_detail"),
    path("menu/create/", DishCreateView.as_view(), name="dish_create"),
    path("menu/<int:pk>/update/", DishUpdateView.as_view(), name="dish_update"),
    path("menu/<int:pk>/delete/", DishDeleteView.as_view(), name="dish_delete"),
    path("menu/<int:pk>/toggle-assign/", toggle_assign_to_dish, name="toggle_dish_assign"),
    path("dish-type/", DishTypeListView.as_view(), name="dish_type_list"),
    path("dish-type/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish_type_delete"),
    path("dish-type/create/", DishTypeCreateView.as_view(), name="dish_type_create"),
    path("cooks/", CooksListView.as_view(), name="cook_list"),
    path("cooks/<int:pk>/", CooksDetailView.as_view(), name="cook_detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook_create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook_update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook_delete"),
    path("cold-store/", IngredientsListView.as_view(), name="ingredients_list"),
    path("cold-store/create", IngredientsCreateView.as_view(), name="ingredients_create"),
    path("cold-store/<int:pk>/delete/", IngredientsDeleteView.as_view(), name="ingredients_delete"),

]

app_name = "kitchen_app"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen_app.urls", namespace="kitchen_app"))
]

kitchen_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username}"


class Ingredient(models.Model):
    name = models.CharField(max_length=55, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class DishType(models.Model):
    name = models.CharField(max_length=55, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=55, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.SET_DEFAULT,
        null=True,
        default="Tasty food",
        related_name="types",
    )
    cooks = models.ManyToManyField(Cook, related_name="dish")
    ingredient = models.ManyToManyField(Ingredient, related_name="ingredients")

    class Meta:
        ordering = ["name"]
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"

    def __str__(self):
        return self.name

kitchen_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from kitchen_app.models import Cook, Dish


class CookCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=55,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish name"})
    )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"

kitchen_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen_app.forms import CookCreationForm, DishSearchForm, DishForm
from kitchen_app.models import (Dish, DishType, Ingredient, Cook)


def index(request):
    num_dishes = Dish.objects.count()
    num_type = DishType.objects.count()
    num_ingredient = Ingredient.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dishes": num_dishes,
        "num_type": num_type,
        "num_ingredient": num_ingredient,
        "num_cooks": num_cooks
    }

    return render(request, "kitchen_app/index.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    template_name = "kitchen_app/dish_list.html"
    context_object_name = "dish_list"
    paginate_by = 5
    queryset = Dish.objects.all().select_related("dish_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    template_name = "kitchen_app/dish_detail.html"
    context_object_name = "dish_detail"


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    template_name = "kitchen_app/dish_form.html"
    form_class = DishForm
    success_url = reverse_lazy("kitchen_app:dish_list")
    context_object_name = "dish_create"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen_app:dish_list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "kitchen_app/dish_confirm_delete.html"
    context_object_name = "dish_to_delete"
    success_url = reverse_lazy("kitchen_app:dish_list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen_app/dish_types_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen_app/dish_type_create.html"
    success_url = reverse_lazy("kitchen_app:dish_type_list")
    context_object_name = "dish_type_create"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen_app/dish_types_confirm_delete.html"
    context_object_name = "dish_type_to_delete"
    success_url = reverse_lazy("kitchen_app:dish_type_list")


class CooksListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    template_name = "kitchen_app/cook_list.html"
    context_object_name = "cook_list"
    paginate_by = 5


class CooksDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    template_name = "kitchen_app/cook_detail.html"
    context_object_name = "cook_detail"


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen_app:cook_list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = 'years_of_experience',
    template_name = "kitchen_app/cook_form.html"
    success_url = reverse_lazy("kitchen_app:cook_list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "kitchen_app/cook_confirm_delete.html"
    context_object_name = "cook_delete"
    success_url = reverse_lazy("kitchen_app:cook_delete")


class IngredientsListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    template_name = "kitchen_app/ingredient_list.html"
    context_object_name = "ingredient_list"
    paginate_by = 5


class IngredientsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    template_name = "kitchen_app/ingredient_create.html"
    context_object_name = "ingredient_create"
    success_url = reverse_lazy("kitchen_app:ingredients_list")


class IngredientsDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    template_name = "kitchen_app/ingredient_confirm_delete.html"
    context_object_name = "ingredient_delete"
    success_url = reverse_lazy("kitchen_app:ingredients_list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dish.all()
    ):
        cook.dish.remove(pk)
    else:
        cook.dish.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen_app:dish_detail", args=[pk]))

templates/kitchen_app/cook_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete cook-user</h1>
  <br>
  <p>Are you sure you want to delete this cook: {{ cook_delete.username }} ?</p>
  <br>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-primary link-to-page">
    <a href="{% url 'kitchen_app:cook_detail' pk=cook_delete.pk %}" class="btn btn-primary link-to-page" style="background-color: cadetblue">Back</a>
  </form>
{% endblock %}

templates/kitchen_app/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook_detail.username }}
    <a href="{% url 'kitchen_app:cook_delete' pk=cook_detail.pk %}" class="btn btn-primary link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen_app:cook_update' pk=cook_detail.pk %}" class="btn btn-primary link-to-page" style="background-color: cadetblue">
      Edit
    </a>
  </h1>
  <p><strong>First name:</strong> {{ cook_detail.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook_detail.last_name }}</p>
  <p><strong>Years of experience: </strong> {{ cook_detail.years_of_experience }}</p>

  <div class="ml-3">
    <h4 style="color: white">Dishes</h4>

    {% for dish in cook_detail.cooks.all %}
      <hr>
      <p><strong>Dish:</strong> {{ dish.name }}</p>
      <p><strong>Category of dish:</strong> {{ dish.dish_type.name }}</p>
    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen_app/cook_form.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook-user</h1>
  <br>
  {% block create_form %}
    {% include "includes/base_form.html" %}
  {% endblock %}
{% endblock %}

templates/kitchen_app/cook_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Our Cooks <a href="{% url 'kitchen_app:cook_create' %}" class="btn btn-primary link-to-page">Add new Cook</a></h1>
  <br>
  <br>
  {% if cook_list %}
    <table class="table table-dark">
      <thead class="thead-dark">
        <tr>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of experience</th>
        </tr>
      </thead>
      {% for cook in cook_list %}
        <tr>
          <td><a href="{% url 'kitchen_app:cook_detail' pk=cook.pk %}" class="table-a">{{ cook.username }}</a></td>
          <td class="tbl-content">{{ cook.first_name }}</td>
          <td class="tbl-content">{{ cook.last_name }}</td>
          <td class="tbl-content">{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no cooks in kitchen service</p>
  {% endif %}
{% endblock %}

templates/kitchen_app/dish_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete dish</h1>
  <br>
  <p>Are you sure you want to delete this dish: {{ dish_to_delete.name }}</p>
  <br>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-primary link-to-page">
    <a href="{% url 'kitchen_app:dish_list' %}" class="btn btn-primary link-to-page" style="background-color: cadetblue">Back</a>
  </form>
{% endblock %}

templates/kitchen_app/dish_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="detail-content">
    <h1>{{ dish_detail.name }}</h1>
    <h3 class="h3-classic">{{ dish_detail.dish_type }}</h3>
    <h3 class="h3-classic">Price: {{ dish_detail.price }}$</h3>
    <p>Description: {{ dish_detail.description }}</p>
    <h3 class="h3-classic">Ingredients:</h3>
      {% if dish_detail.ingredient.count != 0 %}
      <ul class="hr">
        {% for inredient in dish_detail.ingredient.all %}
        <li>
          {{ inredient.name }}
        </li>
        {% endfor %}
        {% else %}
          <p>There are no ingredients here</p>
        {% endif %}
      </ul>
    {% if dish_detail.cooks %}
      <h3 class="h3-classic">Prepared for you
        {% if dish_detail in user.dish.all %}
          <a href="{% url 'kitchen_app:toggle_dish_assign' pk=dish_detail.id %}" class="btn btn-primary">
            Delete me from this dish
          </a>
        {% else %}
          <a href="{% url 'kitchen_app:toggle_dish_assign' pk=dish_detail.id %}" class="btn btn-primary">
            Join cooking
          </a>
      </h3>
    {% endif %}
      <ul>
        {% for cook in dish_detail.cooks.all %}
          <li><p>{{ cook.username }}</p></li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen_app/dish_form.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
  {% block create_form %}
    {% include "includes/base_form.html" %}
  {% endblock %}
{% endblock %}

templates/kitchen_app/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Dish list <a href="{% url 'kitchen_app:dish_create' %}" class="btn btn-primary link-to-page">Add new dish</a></h1>
  <br>
  <br>
  <form action="" method="get" class="example">
    {{ search_form.as_div }}
      <input type="submit" value="🔎" class="btn-search">
  </form>
  <br>
  {% if dish_list %}
    <table class="table table-dark">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Dish type</th>
          <th>Ingredients</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for dish in dish_list %}
        <tr>
          <td><a class="table-a" href="{% url 'kitchen_app:dish_detail' pk=dish.id %}">{{ dish.name }}</a></td>
          <td class="tbl-content">{{ dish.price }}</td>
          <td class="tbl-content">{{ dish.dish_type }}</td>
          <td class="tbl-content">{{ dish.ingredient.count }}</td>
          <td><a class="table-a" href="{% url 'kitchen_app:dish_update' pk=dish.id %}">Edit ⚙ </a></td>
          <td><a class="table-a" href="{% url 'kitchen_app:dish_delete' pk=dish.id %}">Delete 🗑 </a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no dish in kitchen service</p>
  {% endif %}
{% endblock %}

templates/kitchen_app/dish_type_create.html
{% extends "base.html" %}
{% block content %}
  <h1>Add new dish type</h1>
  <br>
  {% block create_form %}
    {% include "includes/base_form.html" %}
  {% endblock %}
{% endblock %}

templates/kitchen_app/dish_types_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete category of dishes</h1>
  <br>
  <p>Are you sure you want to delete the category of dishes: {{ dish_type_to_delete.name }}</p>
  <br>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-primary link-to-page">
    <a href="{% url 'kitchen_app:dish_type_list' %}" class="btn btn-primary link-to-page" style="background-color: cadetblue">Back</a>
  </form>
{% endblock %}

templates/kitchen_app/dish_types_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Dish categories <a href="{% url 'kitchen_app:dish_type_create' %}" class="btn btn-primary link-to-page">Add new category</a></h1>
  <br>
  <br>
  {% if dish_type_list %}
    <table class="table table-dark">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Delete</th>
        </tr>
        </thead>
        {% for dish_type in dish_type_list %}
          <tr>
            <td class="tbl-content">{{ dish_type.name }}</td>
            <td><a class="table-a" href="{% url 'kitchen_app:dish_type_delete' pk=dish_type.pk%}">Delete 🗑 </a></td>
          </tr>
        {% endfor %}
    </table>
  {% else %}
    <p>There are no dish category in kitchen service</p>
  {% endif %}
{% endblock %}

templates/kitchen_app/index.html
{% extends "base.html" %}

{% block content %}
  {% if user.is_authenticated %}
    <span>So Yummy it will Melt Your Heart</span>
    <h1>Our Kitchen Service has:</h1>
    <br>
    <ul>
      <li><h3 style="color: #e6be99">{{ num_type }} categories of dishes</h3></li>
      <li><h3 style="color: #e6be99">and {{ num_dishes }} different dishes</h3></li>
      <li><h3 style="color: #e6be99">that our {{ num_cooks }} chefs will personally prepare for you</h3></li>
      <li><h3 style="color: #e6be99">from more than {{ num_ingredient }} ingredients</h3></li>
    </ul>
    <br>
    <h1><a href="{% url 'kitchen_app:dish_list' %}" class="btn btn-primary link-to-page">See menu</a></h1>
  {% else %}
    <span>So Yummy it will Melt Your Heart</span>
    <h1>Kitchen Service</h1>
    <p>A place where food and coziness compliment each other.</p>
    <p>To see more information you need to login</p>
    <a href="{% url 'login' %}" class="btn btn-primary btn-xl page-scroll">Login</a>
  {% endif %}
{% endblock %}

templates/kitchen_app/ingredient_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>Add new ingredient</h1>
  <br>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/kitchen_app/ingredient_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Ingredients list <a href="{% url 'kitchen_app:ingredients_create' %}" class="btn btn-primary link-to-page">Add new ingredient</a></h1>
  <br>
  <br>
  {% if ingredient_list %}
    <table class="table table-dark">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for ingredient in ingredient_list %}
      <tr>
        <td class="tbl-content">{{ ingredient.name }}</td>
        <td><a class="table-a" href="{% url 'kitchen_app:ingredients_delete' pk=ingredient.pk %}">Delete 🗑 </a></td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are ingredients in cold store</p>
  {% endif %}
{% endblock %}