kitchen_app/urls.py
from django.urls import path, include

from kitchen_app.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeDeleteView,
    DishTypeCreateView,
    CooksListView,
    CooksDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    IngredientsListView,
    IngredientsCreateView,
    IngredientsDeleteView,
    toggle_assign_to_dish
)

urlpatterns = [
    path("", index, name="home_page"),
    path("menu/", DishListView.as_view(), name="dish_list"),
    path("menu/<int:pk>/", DishDetailView.as_view(), name="dish_detail"),
    path("menu/create/", DishCreateView.as_view(), name="dish_create"),
    path("menu/<int:pk>/update/", DishUpdateView.as_view(), name="dish_update"),
    path("menu/<int:pk>/delete/", DishDeleteView.as_view(), name="dish_delete"),
    path("menu/<int:pk>/toggle-assign/", toggle_assign_to_dish, name="toggle_dish_assign"),
    path("dish-type/", DishTypeListView.as_view(), name="dish_type_list"),
    path("dish-type/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish_type_delete"),
    path("dish-type/create/", DishTypeCreateView.as_view(), name="dish_type_create"),
    path("cooks/", CooksListView.as_view(), name="cook_list"),
    path("cooks/<int:pk>/", CooksDetailView.as_view(), name="cook_detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook_create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook_update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook_delete"),
    path("cold-store/", IngredientsListView.as_view(), name="ingredients_list"),
    path("cold-store/create", IngredientsCreateView.as_view(), name="ingredients_create"),
    path("cold-store/<int:pk>/delete/", IngredientsDeleteView.as_view(), name="ingredients_delete"),

]

app_name = "kitchen_app"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen_app.urls", namespace="kitchen_app"))
]

templates/includes/base_form.html
{% load crispy_forms_filters %}
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit" class="btn btn-primary">
</form>

templates/includes/navigation.html
<!--Navigation-->
<nav id="menu" class="navbar">
  <div class="container">
    <div class="navbar-header"><!--<span id="heading" class="visible-xs">Categories</span>-->
      <button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><i class="fa fa-bars"></i></button>
      <a class="navbar-brand" href="">
        <img src="/static/images/logo.png" width="250px"/>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'kitchen_app:home_page' %}">Home</a></li>
        <li><a href="{% url 'kitchen_app:dish_list' %}">Menu</a></li>
        <li><a href="{% url 'kitchen_app:dish_type_list' %}">Dish category</a></li>
        <li><a href="{% url 'kitchen_app:cook_list' %}">Cooks</a></li>
        <li><a href="{% url 'kitchen_app:ingredients_list' %}">Cold store</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li>
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="btn">Prev</a>
      </li>
    {% else %}
      <li class="act">
        <span class="btn act">Prev</span>
      </li>
    {% endif %}
    <li class="act">
      <span class="btn">{{ page_obj.number }}</span>
    </li>
    {% if page_obj.has_next %}
      <li>
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="btn">Next</a>
      </li>
    {% else %}
      <li class="act">
        <span class="btn">Next</span>
      </li>
    {% endif %}
  </ul>
{% endif %}